version: '3'

services:
  # 前端服务
  frontend:
    build: ./packages/app
    ports:
      - "5173:5173"
    volumes:
      - ./packages/app:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["pnpm", "run", "dev", "--host"]

  # 后端服务
  backend:
    build: ./packages/server
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/todolist
    volumes:
      - ./packages/server:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        npm run generate-prisma &&
        npx prisma db push --schema=./app/prisma/schema.prisma &&
        npm run dev
      "

  # 数据库服务
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  db-data:

networks:
  default:
    name: todolist-network
    external: true 